name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Archive build
        run: zip -r app.zip . -x "*.git*"

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: app.zip
